import type { FeedItem, DashboardSummary, WatchlistArea } from '@/types/dashboard';

export const MOCK_FEED_ITEMS: FeedItem[] = [
  // === CITADEL (재난 · 도시 관제) ===
  {
    id: 'ep-disaster-1',
    type: 'citadel',
    title: 'Santa Rosa Island 산불 확산 및 피해 범위 위성 추적',
    description: 'Santa Rosa Island 산불의 확산 경로와 피해 면적을 위성영상으로 분석. 시계열 비교를 통한 연소 범위 산출.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/santa-rosa-island-wildfire-satellite-analysis',
    link_action: 'external',
    metadata: { event_type: 'wildfire', severity: 'critical', location: 'Santa Rosa Island, USA', has_satellite_imagery: true },
    published_at: '2026-07-05T09:00:00Z',
  },
  {
    id: 'ep-disaster-2',
    type: 'citadel',
    title: '자메이카 홍수 피해 위성영상 분석',
    description: '통신망과 도로가 차단된 자메이카 홍수 피해 지역을 위성영상으로 피해 면적 산출 및 복구 우선순위 분석.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/disaster-impact-jamaica-flood-damage-satellite-imagery',
    link_action: 'external',
    metadata: { event_type: 'flood', severity: 'critical', location: 'Jamaica', has_satellite_imagery: true },
    published_at: '2026-07-03T14:00:00Z',
  },
  {
    id: 'ep-disaster-3',
    type: 'citadel',
    title: '2026 파타고니아 산불 피해 분석 (64,468ha)',
    description: '위성 기반 심각도 평가 및 확산 속도 분석. dNBR 지수로 산불 피해 등급 분류.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/2026-patagonia-wildfire-damage-analysis-64468ha-satellite-severity-spread-rate',
    link_action: 'external',
    metadata: { event_type: 'wildfire', severity: 'high', location: 'Patagonia, Chile', has_satellite_imagery: true },
    published_at: '2026-06-28T10:00:00Z',
  },
  {
    id: 'ep-disaster-4',
    type: 'citadel',
    title: '가나 Akosombo 댐 방류 및 Volta강 홍수 확산 분석',
    description: 'Akosombo 댐 긴급 방류 후 Volta강 유역 범람 면적 변화를 위성으로 추적.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/satellite-analysis-akosombo-dam-release-volta-river-flood-ghana',
    link_action: 'external',
    metadata: { event_type: 'flood', severity: 'high', location: 'Ghana', has_satellite_imagery: true },
    published_at: '2026-06-25T08:00:00Z',
  },
  {
    id: 'ep-disaster-5',
    type: 'citadel',
    title: '2026 전남 광양 산불 분석 (NDMI, dNBR)',
    description: '전남 광양시 산불 피해 범위 및 산림 수분 변화를 NDMI, dNBR 지수로 분석.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/2026-gwangyang-wildfire-ndmi-dnbr-analysis',
    link_action: 'external',
    metadata: { event_type: 'wildfire', severity: 'high', location: '전남 광양시', has_satellite_imagery: true },
    published_at: '2026-06-20T09:00:00Z',
  },

  // === PREDICT (자산 검증 · 금융) ===
  {
    id: 'ep-predict-1',
    type: 'predict',
    title: '호르무즈 해협 봉쇄 후 원유 이동 경로 위성 분석',
    description: 'Port of Fujairah와 Yanbu Commercial Port의 원유 저장탱크 변화를 위성으로 추적. 글로벌 공급망 리스크 진단.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/strait-of-hormuz-blockade-oil-rerouting-fujairah-yanbu',
    link_action: 'external',
    metadata: { analysis_type: 'change_detection', location: 'Strait of Hormuz' },
    published_at: '2026-07-04T10:00:00Z',
  },
  {
    id: 'ep-predict-2',
    type: 'predict',
    title: '미국 옥수수 수확량 예측 (97% 정확도 모델)',
    description: '2024-2025 미국 Corn Belt 위성 기반 수확량 예측. Nara Space AI 모델 97% 정확도 달성.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/2025-us-corn-yield-prediction',
    link_action: 'external',
    metadata: { analysis_type: 'ndvi', location: 'US Corn Belt' },
    published_at: '2026-06-30T11:00:00Z',
  },
  {
    id: 'ep-predict-3',
    type: 'predict',
    title: '태양광 발전소 패널 이상 탐지 — 위성 기반 자산 검증',
    description: '전남 해남 태양광 단지 위성영상 분석. 패널 열화·파손 구간 자동 검출로 금융기관 자산 실사 지원.',
    thumbnail_url: null,
    link_url: null,
    link_action: 'external',
    metadata: { analysis_type: 'asset_verification', location: '전남 해남', asset_type: 'solar' },
    published_at: '2026-07-06T09:00:00Z',
  },
  {
    id: 'ep-predict-4',
    type: 'predict',
    title: '범용 자산 검증 — 물류 창고 재고 추정 위성 분석',
    description: '쿠팡 물류센터 주차장·야적장 변화를 위성으로 추적, 분기별 재고 회전율 시그널 산출.',
    thumbnail_url: null,
    link_url: null,
    link_action: 'external',
    metadata: { analysis_type: 'asset_verification', location: '경기 이천', asset_type: 'logistics' },
    published_at: '2026-07-01T10:00:00Z',
  },

  // === WARDEN (기후 · 컴플라이언스) ===
  {
    id: 'ep-warden-1',
    type: 'warden',
    title: 'Raja Ampat 니켈 채굴 허가 취소 후 산림 변화',
    description: '인도네시아 Raja Ampat 니켈 채굴 허가 취소 이후 산림 손실이 멈췄는지 위성영상으로 검증.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/indonesia-raja-ampat-nickel-mining-permits-forest-loss',
    link_action: 'external',
    metadata: { analysis_type: 'ndvi', location: 'Raja Ampat, Indonesia' },
    published_at: '2026-07-03T08:00:00Z',
  },
  {
    id: 'ep-warden-2',
    type: 'warden',
    title: '국내 정유시설 메탄 배출 위성 검증 — EU 규제 대응',
    description: '울산·여수 석유화학 단지의 메탄 배출량을 위성 분광 데이터로 정량화. EU 메탄 규제(2027) 사전 대비.',
    thumbnail_url: null,
    link_url: null,
    link_action: 'external',
    metadata: { analysis_type: 'methane', location: '울산/여수', compliance: 'EU Methane Regulation' },
    published_at: '2026-07-07T08:00:00Z',
  },
  {
    id: 'ep-warden-3',
    type: 'warden',
    title: 'EUDR 공급망 검증 — 코코아 원산지 산림 전용 모니터링',
    description: 'EU 산림전용규제(EUDR) 시행에 따라 코트디부아르·가나 코코아 농장의 산림 전용 여부를 위성으로 검증.',
    thumbnail_url: null,
    link_url: null,
    link_action: 'external',
    metadata: { analysis_type: 'ndvi', location: "Côte d'Ivoire / Ghana", compliance: 'EUDR' },
    published_at: '2026-07-05T11:00:00Z',
  },
  {
    id: 'ep-warden-4',
    type: 'warden',
    title: '동남아 팜 플랜테이션 확장 감시 — 보르네오 위성 분석',
    description: '보르네오 열대우림 내 팜유 플랜테이션 신규 개간 면적을 분기별 위성영상으로 추적.',
    thumbnail_url: null,
    link_url: null,
    link_action: 'external',
    metadata: { analysis_type: 'ndvi', location: 'Borneo, Malaysia/Indonesia', compliance: 'EUDR' },
    published_at: '2026-06-29T09:00:00Z',
  },

  // === NORTHPAPER (국방 · 안보) ===
  {
    id: 'ep-northpaper-1',
    type: 'northpaper',
    title: '위성이 포착한 북한 5대 조선소 구조 변화',
    description: '남포, 신포, 마양도, 청진, 라진 — 5개 핵심 조선소·항만의 위성영상 비교 분석.',
    thumbnail_url: null,
    link_url: '/interactive/north-korean-shipyards',
    link_action: 'navigate',
    metadata: { analysis_type: 'change_detection', location: 'North Korea', platform: 'northpaper' },
    published_at: '2026-07-05T08:00:00Z',
  },
  {
    id: 'ep-northpaper-2',
    type: 'northpaper',
    title: '이란 핵시설 공습 피해 위성영상 분석',
    description: '이란 핵시설에 대한 공습 피해를 위성영상으로 확인. 시설 구조 변화 및 피해 규모 평가.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/iran-nuclear-facilities-airstrike-damage-satellite',
    link_action: 'external',
    metadata: { analysis_type: 'change_detection', location: 'Iran', platform: 'northpaper' },
    published_at: '2026-06-28T15:00:00Z',
  },

  // === SHORTS (YouTube) ===
  {
    id: 'yt-shorts-1',
    type: 'shorts',
    title: '위성영상으로 북한 조선소의 변화를 포착하다',
    description: '사라진 북한 선박의 행방 — 5대 조선소 구조 변화 위성 분석',
    thumbnail_url: null,
    link_url: 'https://www.youtube.com/shorts/_oLIheApG44',
    link_action: 'external',
    metadata: { duration_sec: 58, views: 2500, youtube_id: '_oLIheApG44' },
    published_at: '2026-07-01T12:00:00Z',
  },
  {
    id: 'yt-shorts-2',
    type: 'shorts',
    title: '위성영상으로 홍수 피해를 분석하다',
    description: '통신망과 도로가 차단된 홍수 피해 지역을 어떻게 분석할까?',
    thumbnail_url: null,
    link_url: 'https://www.youtube.com/shorts/GxZUl9a5aZQ',
    link_action: 'external',
    metadata: { duration_sec: 52, views: 1600, youtube_id: 'GxZUl9a5aZQ' },
    published_at: '2026-06-28T10:00:00Z',
  },
  {
    id: 'yt-shorts-3',
    type: 'shorts',
    title: '호르무즈 봉쇄 이후 원유는 정말 이동을 멈췄을까?',
    description: '위성영상으로 공급망 리스크를 진단하다',
    thumbnail_url: null,
    link_url: 'https://www.youtube.com/shorts/okv8NtxV9Oc',
    link_action: 'external',
    metadata: { duration_sec: 45, views: 729, youtube_id: 'okv8NtxV9Oc' },
    published_at: '2026-06-25T14:00:00Z',
  },
  {
    id: 'yt-shorts-4',
    type: 'shorts',
    title: 'NASA 아르테미스 II에 탑재된 K-RadCube',
    description: '나라스페이스는 어떻게 해냈나 — NASA 인증 우주 방사선 모니터',
    thumbnail_url: null,
    link_url: 'https://www.youtube.com/shorts/ODQyuOXDZhk',
    link_action: 'external',
    metadata: { duration_sec: 60, views: 1100, youtube_id: 'ODQyuOXDZhk' },
    published_at: '2026-06-22T09:00:00Z',
  },
  {
    id: 'yt-shorts-5',
    type: 'shorts',
    title: '위성이 포착한 홍수 피해, 숫자로 증명하다',
    description: 'EarthPaper 위성 데이터 분석으로 홍수 피해 면적 산출',
    thumbnail_url: null,
    link_url: 'https://www.youtube.com/shorts/dNqJ90NR-LE',
    link_action: 'external',
    metadata: { duration_sec: 48, views: 1600, youtube_id: 'dNqJ90NR-LE' },
    published_at: '2026-06-18T11:00:00Z',
  },

  // === NEWS ===
  {
    id: 'ep-news-1',
    type: 'news',
    title: '글로벌 초콜릿 가격 급등 — 코코아 재고 폭락의 위성 분석',
    description: '코코아 주산지 서아프리카의 작황을 위성으로 모니터링. 재고 감소와 가격 상승 상관관계 분석.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/global-chocolate-prices-soar-cocoa-stocks',
    link_action: 'external',
    metadata: { source: 'EarthPaper', category: 'finance' },
    published_at: '2026-07-02T10:00:00Z',
  },
  {
    id: 'ep-news-2',
    type: 'news',
    title: 'Tesla 생산 변동과 주가 — 위성이 포착한 단서',
    description: '테슬라 기가팩토리 주차장 재고와 생산라인 가동률을 위성영상으로 추적.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/tesla-production-satellite-clues',
    link_action: 'external',
    metadata: { source: 'EarthPaper', category: 'finance' },
    published_at: '2026-06-29T08:00:00Z',
  },
  {
    id: 'ep-news-3',
    type: 'news',
    title: '금강산 관광지구 철거 현황과 전망',
    description: '북한 금강산 관광지구 시설 철거 진행 상황을 위성으로 모니터링.',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/kumgangsan-tourist-area-demolition',
    link_action: 'external',
    metadata: { source: 'EarthPaper', category: 'defense' },
    published_at: '2026-06-27T09:00:00Z',
  },

  // === TRENDING ===
  {
    id: 'ep-trending-1',
    type: 'trending',
    title: '북한 조선소 5곳 구조 변화',
    description: '위성영상으로 포착한 북한 주요 조선소 변화 분석',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/satellite-imagery-changes-five-major-north-korean-shipyards-ports',
    link_action: 'external',
    metadata: { rank: 1, resolution: 'Defense', satellite: 'SpaceEye-T' },
    published_at: '2026-07-05T06:00:00Z',
  },
  {
    id: 'ep-trending-2',
    type: 'trending',
    title: 'Santa Rosa Island 산불',
    description: 'California 산불 확산 위성 추적',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/santa-rosa-island-wildfire-satellite-analysis',
    link_action: 'external',
    metadata: { rank: 2, resolution: 'Disaster', satellite: 'Observer' },
    published_at: '2026-07-05T06:00:00Z',
  },
  {
    id: 'ep-trending-3',
    type: 'trending',
    title: '호르무즈 해협 원유 이동',
    description: '봉쇄 후 글로벌 원유 공급망 변화',
    thumbnail_url: null,
    link_url: 'https://ep.naraspace.com/post/contents/strait-of-hormuz-blockade-oil-rerouting-fujairah-yanbu',
    link_action: 'external',
    metadata: { rank: 3, resolution: 'Finance', satellite: 'SpaceEye-T' },
    published_at: '2026-07-05T06:00:00Z',
  },
];

export const MOCK_WATCHLIST: WatchlistArea[] = [];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  dailyScene: {
    id: 'scene-daily-1',
    satellite: 'SpaceEye-T',
    location: '서울 여의도',
    acquired_at: '2026-07-05T02:30:00Z',
    resolution: '30cm',
    thumbnail_url: null,
  },
  editorPick: {
    id: 'ep-original-1',
    tag: 'Northpaper',
    title: '위성이 포착한 북한 5대 조선소 — 사라진 선박의 행방',
    description: '북한 주요 조선소 5곳의 구조 변화를 고해상도 위성영상으로 분석합니다. 선박 건조 현황, 시설 확장, 그리고 사라진 선박들의 이동 경로를 추적합니다.',
    link_url: '/interactive/north-korean-shipyards',
    published_at: '2026-07-05T08:00:00Z',
    source: 'Northpaper 편집팀',
  },
  recentOrders: [
    { id: 'ord-1', status: 'completed', aoi_area_km2: 42, total_price: 630, created_at: '2026-07-02T10:00:00Z' },
    { id: 'ord-2', status: 'processing', aoi_area_km2: 15, total_price: 225, created_at: '2026-07-01T14:00:00Z' },
  ],
  stats: {
    totalImages: 12,
    totalAreaKm2: 480,
    memberSince: '2026-03-15',
  },
  watchlist: MOCK_WATCHLIST,
  pendingTaskings: 1,
};
